---
title: "New Skills"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ca-new_skills}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# New Skills

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup new skills}
library(skillsNet)
library(ggplot2) 
library(treemapify)
library(dplyr)
library(tidyr)
library(ggplot2)
library(tibble)
library(plotly)
library(ggfittext)
```

This Vignette contains the process for generating the recent skills acquired plot


## Data Manipulation

```{r Extract from triplet table}
skillsNet::test_data %>% 
  # filtering for only the specific skills
  filter(grepl("ss-.*", Origin)) %>% 
  
  #filtering for only the relevant relationships
  filter(Relationship %in% c("has.root", "has.weight", "has.comp.date")) %>% 
  
  # spreading for the tabular pref
  spread(key = Relationship, value = Value) %>% 
  
  # applying types
  mutate_all(reTypeVect) %>% 
  
  # filtering only the most recent events
  filter(!is.na(has.comp.date), has.comp.date > Sys.Date() - lubridate::days(100)) ->
    skills_gained_recently


```


```{r generate correct treemap structure}
treeMapCoordinates <- treemapify(skills_gained_recently,
                                 area = "has.weight",
                                 fill = "has.root",
                                 label = "Origin",
                                 group = "has.root") %>% 
  group_by(Origin) %>% 
  mutate(xpos = mean(c(xmin, xmax)), ypos = mean(c(ymin, ymax))) %>% 
  ungroup() %>% 
  mutate(Origin = gsub(".*-", "", Origin))
```
## Plotting

```{r making basic plot, fig.height= 08, fig.width=09}
treeMapCoordinates %>% 
  ggplot(aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax)) +
  geom_rect(aes(fill = has.root), colour = "white") +
  geom_fit_text(aes(x = xpos, y = ypos, label = Origin)) +
  labs(
    fill = "Root Skill"
    , title = "Mosaic Plot of the skills learned in the last 100 days"
  ) +
  theme_bw() +
  theme(
    axis.title.y = element_blank()
    , axis.title.x = element_blank()
    , axis.ticks = element_blank()
    , axis.text = element_blank()
  ) -> coord_plot

coord_plot
```


